<?php
/**
*
* @package Cold Zone
* @copyright (c) 2009-2011 Yuri nE0sIghT Konotopov, http://coldzone.ru
* @license GNU Affero General Public License, version 3 http://www.gnu.org/licenses/agpl-3.0.html
*
*/

if (!defined('IN_GAME'))
{
	exit;
}

class vars
{
	public static $db_fields = array(

		MESSAGE_NEW			=> false, // DEPRECATED
		MESSAGE_SPY			=> 'mnl_spy',
		MESSAGE_JOUER			=> 'mnl_joueur',
		MESSAGE_ALLIANCE		=> 'mnl_alliance',
		MESSAGE_ATTACK			=> 'mnl_attaque',
		MESSAGE_EXPLOIT			=> 'mnl_exploit',
		MESSAGE_TRANSPORT		=> 'mnl_transport',
		MESSAGE_EXPEDITION		=> 'mnl_expedition',
		MESSAGE_BUILDLIST		=> 'mnl_buildlist',
		MESSAGE_ADMIN			=> 'mnl_general',

		BUILDING_METALL_MINE		=> 'metal_mine',
		BUILDING_CRYSTAL_MINE		=> 'crystal_mine',
		BUILDING_DEUTERIUM_SINTHEZER	=> 'deuterium_sintetizer',
		BUILDING_SOLAR_PLANT		=> 'solar_plant',
		BUILDING_FUSION_PLANT		=> 'fusion_plant',
		BUILDING_ROBOT_FACTORY		=> 'robot_factory',
		BUILDING_NANO_FACTORY		=> 'nano_factory',
		BUILDING_HANGAR			=> 'hangar',
		BUILDING_METAL_STORE		=> 'metal_store',
		BUILDING_CRYSTAL_STORE		=> 'crystal_store',
		BUILDING_DEUTERIUM_STORE	=> 'deuterium_store',
		BUILDING_LABORATORY		=> 'laboratory',
		BUILDING_TERRAFORMER		=> 'terraformer',
		BUILDING_ALLY_DEPOSIT		=> 'ally_deposit',
		BUILDING_MONDBASIS		=> 'mondbasis',
		BUILDING_PHALANX		=> 'phalanx',
		BUILDING_SPRUNGTOR		=> 'sprungtor',
		BUILDING_SILO			=> 'silo',

		TECH_SPY			=> 'spy_tech',
		TECH_COMPUTER			=> 'computer_tech',
		TECH_MILITARY			=> 'military_tech',
		TECH_DEFENCE			=> 'shield_tech', // XNova coders is something... Shield -> defence, Defence -> shield omg. Need workaround: nS
		TECH_SHIELD			=> 'defence_tech', 
		TECH_ENERGY			=> 'energy_tech',
		TECH_HYPERSPACE			=> 'hyperspace_tech',
		TECH_COMBUSTION			=> 'combustion_tech',
		TECH_IMPULSE_DRIVE		=> 'impulse_motor_tech',
		TECH_HYPERSPACE_DRIVE		=> 'hyperspace_motor_tech',
		TECH_LASER			=> 'laser_tech',
		TECH_IONIC			=> 'ionic_tech',
		TECH_BUSTER			=> 'buster_tech',
		TECH_INTERGALACTIC		=> 'intergalactic_tech',
		TECH_EXPEDITION			=> 'expedition_tech',
		TECH_COLONIZATION		=> 'colonization_tech',
		TECH_GRAVITON			=> 'graviton_tech',

		SHIP_TRANSPORT_SMALL		=> 'small_ship_cargo',
		SHIP_TRANSPORT_BIG		=> 'big_ship_cargo',
		SHIP_HUNTER_LIGHT		=> 'light_hunter',
		SHIP_HUNTER_HEAVY		=> 'heavy_hunter',
		SHIP_CRUSHER			=> 'crusher',
		SHIP_LINKOR			=> 'battle_ship',
		SHIP_COLONIZER			=> 'colonizer',
		SHIP_RECYCLER			=> 'recycler',
		SHIP_SPY			=> 'spy_sonde',
		SHIP_BOMBER			=> 'bomber_ship',
		SHIP_SOLAR_SATELITE		=> 'solar_satelit',
		SHIP_DESTRUCTOR			=> 'destructor',
		SHIP_DEATH_STAR			=> 'dearth_star',
		SHIP_LINECRUSHER		=> 'battleship',
		SHIP_SUPERNOVA			=> 'supernova',

		DEFENCE_MISSILE_LAUNCHER	=> 'misil_launcher',
		DEFENCE_LASER_SMALL		=> 'small_laser',
		DEFENCE_LASER_BIG		=> 'big_laser',
		DEFENCE_GAUSS_CANNON		=> 'gauss_canyon',
		DEFENCE_IONIC_CANNON		=> 'ionic_canyon',
		DEFENCE_BUSTER_CANNON		=> 'buster_canyon',
		DEFENCE_SHIELD_SMALL		=> 'small_protection_shield',
		DEFENCE_SHIELD_BIG		=> 'big_protection_shield',
		DEFENCE_PROTECTOR		=> 'planet_protector',

		MISSILE_INTERCEPTOR		=> 'interceptor_misil',
		MISSILE_INTERPLANETARY		=> 'interplanetary_misil',

		RPG_GEOLOGUE			=> 'rpg_geologue',
		RPG_ADMIRAL			=> 'rpg_amiral',
		RPG_ENGINEER			=> 'rpg_ingenieur',
		RPG_TECHNOCRATE			=> 'rpg_technocrate',
		RPG_CONSTRUCTOR			=> 'rpg_constructeur',
		RPG_SCIENTIST			=> 'rpg_scientifique',
		RPG_STOCKER			=> 'rpg_stockeur',
		RPG_DEFENSER			=> 'rpg_defenseur',
		RPG_BUNKER			=> 'rpg_bunker',
		RPG_ESPION			=> 'rpg_espion',
		RPG_COMMANDANT			=> 'rpg_commandant',
		RPG_DESTRUCTOR			=> 'rpg_destructeur',
		RPG_GENERAL			=> 'rpg_general',
		RPG_RIDER			=> 'rpg_raideur',
		RPG_EMPEROR			=> 'rpg_empereur',
		RPG_GEODESIST			=> 'rpg_geodesist',
		RPG_AIDEDECAMP			=> 'rpg_aidedecamp',
	);
	
	public static $requeriments = array(
		BUILDING_FUSION_PLANT			=> array(
			BUILDING_DEUTERIUM_SINTHEZER			=> 5,
			TECH_ENERGY			=> 3,
		),
		BUILDING_NANO_FACTORY			=> array(
			BUILDING_ROBOT_FACTORY			=> 10,
			TECH_COMPUTER			=> 10,
		),
		BUILDING_HANGAR			=> array(
			BUILDING_ROBOT_FACTORY			=> 2,
		),
		BUILDING_TERRAFORMER			=> array(
			BUILDING_NANO_FACTORY			=> 1,
			TECH_ENERGY			=> 12,
		),
		BUILDING_PHALANX			=> array(
			BUILDING_MONDBASIS			=> 1,
		),
		BUILDING_SPRUNGTOR			=> array(
			BUILDING_MONDBASIS			=> 1,
			TECH_HYPERSPACE			=> 7,
		),
		TECH_SPY			=> array(
			BUILDING_LABORATORY			=> 3,
		),
		TECH_COMPUTER			=> array(
			BUILDING_LABORATORY			=> 1,
		),
		TECH_MILITARY			=> array(
			BUILDING_LABORATORY			=> 4,
		),
		TECH_SHIELD			=> array(
			TECH_ENERGY			=> 3,
			BUILDING_LABORATORY			=> 6,
		),
		TECH_DEFENCE			=> array(
			BUILDING_LABORATORY			=> 2,
		),
		TECH_ENERGY			=> array(
			BUILDING_LABORATORY			=> 1,
		),
		TECH_HYPERSPACE			=> array(
			TECH_ENERGY			=> 5,
			TECH_SHIELD			=> 5,
			BUILDING_LABORATORY			=> 7,
		),
		TECH_COMBUSTION			=> array(
			TECH_ENERGY			=> 1,
			BUILDING_LABORATORY			=> 1,
		),
		TECH_IMPULSE_DRIVE			=> array(
			TECH_ENERGY			=> 1,
			BUILDING_LABORATORY			=> 2,
		),
		TECH_HYPERSPACE_DRIVE			=> array(
			TECH_HYPERSPACE			=> 3,
			BUILDING_LABORATORY			=> 7,
		),
		TECH_LASER			=> array(
			BUILDING_LABORATORY			=> 1,
			TECH_ENERGY			=> 2,
		),
		TECH_IONIC			=> array(
			BUILDING_LABORATORY			=> 4,
			TECH_LASER			=> 5,
			TECH_ENERGY			=> 4,
		),
		TECH_BUSTER			=> array(
			BUILDING_LABORATORY			=> 5,
			TECH_ENERGY			=> 8,
			TECH_LASER			=> 10,
			TECH_IONIC			=> 5,
		),
		TECH_INTERGALACTIC			=> array(
			BUILDING_LABORATORY			=> 10,
			TECH_COMPUTER			=> 8,
			TECH_HYPERSPACE			=> 8,
		),
		TECH_EXPEDITION			=> array(
			BUILDING_LABORATORY			=> 3,
			TECH_COMPUTER			=> 4,
			TECH_IMPULSE_DRIVE			=> 3,
		),
		TECH_COLONIZATION			=> array(
			TECH_EXPEDITION			=> 1,
			TECH_SPY			=> 3,
		),
		TECH_GRAVITON			=> array(
			BUILDING_LABORATORY			=> 12,
		),
		SHIP_TRANSPORT_SMALL			=> array(
			BUILDING_HANGAR			=> 2,
			TECH_COMBUSTION			=> 2,
		),
		SHIP_TRANSPORT_BIG			=> array(
			BUILDING_HANGAR			=> 4,
			TECH_COMBUSTION			=> 6,
		),
		SHIP_HUNTER_LIGHT			=> array(
			BUILDING_HANGAR			=> 1,
			TECH_COMBUSTION			=> 1,
		),
		SHIP_HUNTER_HEAVY			=> array(
			BUILDING_HANGAR			=> 3,
			TECH_DEFENCE			=> 2,
			TECH_IMPULSE_DRIVE			=> 2,
		),
		SHIP_CRUSHER			=> array(
			BUILDING_HANGAR			=> 5,
			TECH_IMPULSE_DRIVE			=> 4,
			TECH_IONIC			=> 2,
		),
		SHIP_LINKOR			=> array(
			BUILDING_HANGAR			=> 7,
			TECH_HYPERSPACE_DRIVE			=> 4,
		),
		SHIP_COLONIZER			=> array(
			BUILDING_HANGAR			=> 4,
			TECH_COLONIZATION			=> 1,
		),
		SHIP_RECYCLER			=> array(
			BUILDING_HANGAR			=> 4,
			TECH_COMBUSTION			=> 6,
			TECH_SHIELD			=> 2,
		),
		SHIP_SPY			=> array(
			BUILDING_HANGAR			=> 3,
			TECH_COMBUSTION			=> 3,
			TECH_SPY			=> 2,
		),
		SHIP_BOMBER			=> array(
			TECH_IMPULSE_DRIVE			=> 6,
			BUILDING_HANGAR			=> 8,
			TECH_BUSTER			=> 5,
		),
		SHIP_SOLAR_SATELITE			=> array(
			BUILDING_HANGAR			=> 1,
		),
		SHIP_DESTRUCTOR			=> array(
			BUILDING_HANGAR			=> 9,
			TECH_HYPERSPACE_DRIVE			=> 6,
			TECH_HYPERSPACE			=> 5,
		),
		SHIP_DEATH_STAR			=> array(
			BUILDING_HANGAR			=> 12,
			TECH_HYPERSPACE_DRIVE			=> 7,
			TECH_HYPERSPACE			=> 6,
			TECH_GRAVITON			=> 1,
		),
		SHIP_LINECRUSHER			=> array(
			TECH_HYPERSPACE			=> 5,
			TECH_LASER			=> 12,
			TECH_HYPERSPACE_DRIVE			=> 5,
			BUILDING_HANGAR			=> 8,
		),
		SHIP_SUPERNOVA			=> array(
			RPG_RIDER			=> 1,
		),
		DEFENCE_MISSILE_LAUNCHER			=> array(
			BUILDING_HANGAR			=> 1,
		),
		DEFENCE_LASER_SMALL			=> array(
			TECH_ENERGY			=> 1,
			BUILDING_HANGAR			=> 2,
			TECH_LASER			=> 3,
		),
		DEFENCE_LASER_BIG			=> array(
			TECH_ENERGY			=> 3,
			BUILDING_HANGAR			=> 4,
			TECH_LASER			=> 6,
		),
		DEFENCE_GAUSS_CANNON			=> array(
			BUILDING_HANGAR			=> 6,
			TECH_ENERGY			=> 6,
			TECH_MILITARY			=> 3,
			TECH_SHIELD			=> 1,
		),
		DEFENCE_IONIC_CANNON			=> array(
			BUILDING_HANGAR			=> 4,
			TECH_IONIC			=> 4,
		),
		DEFENCE_BUSTER_CANNON			=> array(
			BUILDING_HANGAR			=> 8,
			TECH_BUSTER			=> 7,
		),
		DEFENCE_SHIELD_SMALL			=> array(
			TECH_SHIELD			=> 2,
			BUILDING_HANGAR			=> 1,
		),
		DEFENCE_SHIELD_BIG			=> array(
			TECH_SHIELD			=> 6,
			BUILDING_HANGAR			=> 6,
		),
		DEFENCE_PROTECTOR			=> array(
			RPG_BUNKER			=> 1,
		),
		MISSILE_INTERCEPTOR			=> array(
			BUILDING_SILO			=> 2,
		),
		MISSILE_INTERPLANETARY			=> array(
			BUILDING_SILO			=> 4,
		),
		RPG_ENGINEER			=> array(
			RPG_GEOLOGUE			=> 5,
		),
		RPG_TECHNOCRATE			=> array(
			RPG_ADMIRAL			=> 5,
		),
		RPG_CONSTRUCTOR			=> array(
			RPG_GEOLOGUE			=> 10,
			RPG_ENGINEER			=> 2,
		),
		RPG_SCIENTIST			=> array(
			RPG_GEOLOGUE			=> 10,
			RPG_ENGINEER			=> 2,
		),
		RPG_STOCKER			=> array(
			RPG_CONSTRUCTOR			=> 1,
		),
		RPG_DEFENSER			=> array(
			RPG_SCIENTIST			=> 1,
		),
	/*	RPG_BUNKER			=> array(
			RPG_GEOLOGUE			=> 20,
			RPG_ENGINEER			=> 10,
			RPG_CONSTRUCTOR			=> 3,
			RPG_SCIENTIST			=> 3,
			RPG_STOCKER			=> 2,
			RPG_DEFENSER			=> 2,
		),*/
		RPG_ESPION			=> array(
			RPG_ADMIRAL			=> 10,
			RPG_TECHNOCRATE			=> 5,
		),
		RPG_COMMANDANT			=> array(
			RPG_ADMIRAL			=> 10,
			RPG_TECHNOCRATE			=> 5,
		),
		RPG_DESTRUCTOR			=> array(
			RPG_ESPION			=> 1,
		),
		RPG_GENERAL			=> array(
			RPG_COMMANDANT			=> 1,
		),
		RPG_GEODESIST			=> array(
			RPG_GEOLOGUE			=> 20,
			RPG_ENGINEER			=> 6,
			RPG_STOCKER			=> 2,
			RPG_CONSTRUCTOR			=> 3,
		),
		RPG_AIDEDECAMP			=> array(
			RPG_ADMIRAL			=> 20,
			RPG_GENERAL			=> 5,
		),
	/*	RPG_RIDER			=> array(
			RPG_ADMIRAL			=> 20,
			RPG_TECHNOCRATE			=> 10,
			RPG_ESPION			=> 2,
			RPG_COMMANDANT			=> 2,
			RPG_DESTRUCTOR			=> 1,
			RPG_GENERAL			=> 3,
		),
		RPG_EMPEROR			=> array(
			RPG_RIDER			=> 1,
			RPG_BUNKER			=> 1,
		),*/
	);
	
	public static $params = array(
		BUILDING_METALL_MINE			=> array(
			'metal'			=> 60,
			'crystal'			=> 15,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.5,
		),
		BUILDING_CRYSTAL_MINE			=> array(
			'metal'			=> 48,
			'crystal'			=> 24,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.6,
		),
		BUILDING_DEUTERIUM_SINTHEZER			=> array(
			'metal'			=> 225,
			'crystal'			=> 75,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.5,
		),
		BUILDING_SOLAR_PLANT			=> array(
			'metal'			=> 75,
			'crystal'			=> 30,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.5,
		),
		BUILDING_FUSION_PLANT			=> array(
			'metal'			=> 900,
			'crystal'			=> 360,
			'deuterium'			=> 180,
			'energy'			=> 0,
			'factor'			=> 1.8,
		),
		BUILDING_ROBOT_FACTORY			=> array(
			'metal'			=> 400,
			'crystal'			=> 120,
			'deuterium'			=> 200,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_NANO_FACTORY			=> array(
			'metal'			=> 1000000,
			'crystal'			=> 500000,
			'deuterium'			=> 100000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_HANGAR			=> array(
			'metal'			=> 400,
			'crystal'			=> 200,
			'deuterium'			=> 100,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_METAL_STORE			=> array(
			'metal'			=> 2000,
			'crystal'			=> 0,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_CRYSTAL_STORE			=> array(
			'metal'			=> 2000,
			'crystal'			=> 1000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_DEUTERIUM_STORE			=> array(
			'metal'			=> 2000,
			'crystal'			=> 2000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_LABORATORY			=> array(
			'metal'			=> 200,
			'crystal'			=> 400,
			'deuterium'			=> 200,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_TERRAFORMER			=> array(
			'metal'			=> 0,
			'crystal'			=> 50000,
			'deuterium'			=> 100000,
			'energy'			=> 1000,
			'factor'			=> 2,
		),
		BUILDING_ALLY_DEPOSIT			=> array(
			'metal'			=> 20000,
			'crystal'			=> 40000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_MONDBASIS			=> array(
			'metal'			=> 20000,
			'crystal'			=> 40000,
			'deuterium'			=> 20000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_PHALANX			=> array(
			'metal'			=> 20000,
			'crystal'			=> 40000,
			'deuterium'			=> 20000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_SPRUNGTOR			=> array(
			'metal'			=> 2000000,
			'crystal'			=> 4000000,
			'deuterium'			=> 2000000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		BUILDING_SILO			=> array(
			'metal'			=> 20000,
			'crystal'			=> 20000,
			'deuterium'			=> 1000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_SPY			=> array(
			'metal'			=> 200,
			'crystal'			=> 1000,
			'deuterium'			=> 200,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_COMPUTER			=> array(
			'metal'			=> 0,
			'crystal'			=> 400,
			'deuterium'			=> 600,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_MILITARY			=> array(
			'metal'			=> 800,
			'crystal'			=> 200,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_SHIELD			=> array(
			'metal'			=> 200,
			'crystal'			=> 600,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_DEFENCE			=> array(
			'metal'			=> 1000,
			'crystal'			=> 0,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_ENERGY			=> array(
			'metal'			=> 0,
			'crystal'			=> 800,
			'deuterium'			=> 400,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_HYPERSPACE			=> array(
			'metal'			=> 0,
			'crystal'			=> 4000,
			'deuterium'			=> 2000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_COMBUSTION			=> array(
			'metal'			=> 400,
			'crystal'			=> 0,
			'deuterium'			=> 600,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_IMPULSE_DRIVE			=> array(
			'metal'			=> 2000,
			'crystal'			=> 4000,
			'deuterium'			=> 600,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_HYPERSPACE_DRIVE			=> array(
			'metal'			=> 10000,
			'crystal'			=> 20000,
			'deuterium'			=> 6000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_LASER			=> array(
			'metal'			=> 200,
			'crystal'			=> 100,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_IONIC			=> array(
			'metal'			=> 1000,
			'crystal'			=> 300,
			'deuterium'			=> 100,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_BUSTER			=> array(
			'metal'			=> 2000,
			'crystal'			=> 4000,
			'deuterium'			=> 1000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_INTERGALACTIC			=> array(
			'metal'			=> 240000,
			'crystal'			=> 400000,
			'deuterium'			=> 160000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_EXPEDITION			=> array(
			'metal'			=> 4000,
			'crystal'			=> 8000,
			'deuterium'			=> 4000,
			'energy'			=> 0,
			'factor'			=> 2,
		),
		TECH_COLONIZATION			=> array(
			'metal'			=> 4000,
			'crystal'			=> 8000,
			'deuterium'			=> 4000,
			'energy'			=> 0,
			'factor'			=> 2,
			'max'				=> MAX_COLONIZATION_LEVEL,
		),
		TECH_GRAVITON			=> array(
			'metal'			=> 0,
			'crystal'			=> 0,
			'deuterium'			=> 0,
			'energy_max'			=> 300000,
			'factor'			=> 3,
		),
		SHIP_TRANSPORT_SMALL			=> array(
			'metal'			=> 2000,
			'crystal'			=> 2000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 20,
			'consumption2'			=> 40,
			'speed'				=> 5000,
			'speed2'			=> 10000,
			'speed_ex'			=> array(
				TECH_IMPULSE_DRIVE		=> 5
			),
			'capacity'			=> 5000,
		),
		SHIP_TRANSPORT_BIG			=> array(
			'metal'			=> 6000,
			'crystal'			=> 6000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 50,
			'consumption2'			=> 50,
			'speed'			=> 7500,
			'speed2'			=> 7500,
			'capacity'			=> 25000,
		),
		SHIP_HUNTER_LIGHT			=> array(
			'metal'			=> 3000,
			'crystal'			=> 1000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 20,
			'consumption2'			=> 20,
			'speed'			=> 12500,
			'speed2'			=> 12500,
			'capacity'			=> 50,
		),
		SHIP_HUNTER_HEAVY			=> array(
			'metal'			=> 6000,
			'crystal'			=> 4000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 75,
			'consumption2'			=> 75,
			'speed'			=> 10000,
			'speed2'			=> 15000,
			'capacity'			=> 100,
		),
		SHIP_CRUSHER			=> array(
			'metal'			=> 20000,
			'crystal'			=> 7000,
			'deuterium'			=> 2000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 300,
			'consumption2'			=> 300,
			'speed'			=> 15000,
			'speed2'			=> 15000,
			'capacity'			=> 800,
		),
		SHIP_LINKOR			=> array(
			'metal'			=> 45000,
			'crystal'			=> 15000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 500,
			'consumption2'			=> 500,
			'speed'			=> 10000,
			'speed2'			=> 10000,
			'capacity'			=> 1500,
		),
		SHIP_COLONIZER			=> array(
			'metal'			=> 10000,
			'crystal'			=> 20000,
			'deuterium'			=> 10000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 1000,
			'consumption2'			=> 1000,
			'speed'			=> 2500,
			'speed2'			=> 2500,
			'capacity'			=> 7500,
		),
		SHIP_RECYCLER			=> array(
			'metal'			=> 10000,
			'crystal'			=> 6000,
			'deuterium'			=> 2000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 300,
			'consumption2'			=> 300,
			'speed'			=> 2000,
			'speed2'			=> 2000,
			'capacity'			=> 20000,
		),
		SHIP_SPY			=> array(
			'metal'			=> 0,
			'crystal'			=> 1000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 1,
			'consumption2'			=> 1,
			'speed'			=> 100000000,
			'speed2'			=> 100000000,
			'capacity'			=> 5,
		),
		SHIP_BOMBER			=> array(
			'metal'			=> 50000,
			'crystal'			=> 25000,
			'deuterium'			=> 15000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 1000,
			'consumption2'			=> 1000,
			'speed'			=> 4000,
			'speed2'			=> 5000,
			'capacity'			=> 500,
		),
		SHIP_SOLAR_SATELITE			=> array(
			'metal'			=> 0,
			'crystal'			=> 2000,
			'deuterium'			=> 500,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 0,
			'consumption2'			=> 0,
			'speed'			=> 0,
			'speed2'			=> 0,
			'capacity'			=> 0,
		),
		SHIP_DESTRUCTOR			=> array(
			'metal'			=> 60000,
			'crystal'			=> 50000,
			'deuterium'			=> 15000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 1000,
			'consumption2'			=> 1000,
			'speed'			=> 5000,
			'speed2'			=> 5000,
			'capacity'			=> 2000,
		),
		SHIP_DEATH_STAR			=> array(
			'metal'			=> 5000000,
			'crystal'			=> 4000000,
			'deuterium'			=> 1000000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 1,
			'consumption2'			=> 1,
			'speed'			=> 100,
			'speed2'			=> 100,
			'capacity'			=> 1000000,
		),
		SHIP_LINECRUSHER			=> array(
			'metal'			=> 30000,
			'crystal'			=> 40000,
			'deuterium'			=> 15000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 250,
			'consumption2'			=> 250,
			'speed'			=> 10000,
			'speed2'			=> 10000,
			'capacity'			=> 750,
		),
		SHIP_SUPERNOVA			=> array(
			'metal'			=> 20000000,
			'crystal'			=> 15000000,
			'deuterium'			=> 5000000,
			'energy'			=> 0,
			'factor'			=> 1,
			'consumption'			=> 250,
			'consumption2'			=> 250,
			'speed'			=> 150,
			'speed2'			=> 150,
			'capacity'			=> 2000000,
		),
		DEFENCE_MISSILE_LAUNCHER			=> array(
			'metal'			=> 2000,
			'crystal'			=> 0,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_LASER_SMALL			=> array(
			'metal'			=> 1500,
			'crystal'			=> 500,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_LASER_BIG			=> array(
			'metal'			=> 6000,
			'crystal'			=> 2000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_GAUSS_CANNON			=> array(
			'metal'			=> 20000,
			'crystal'			=> 15000,
			'deuterium'			=> 2000,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_IONIC_CANNON			=> array(
			'metal'			=> 2000,
			'crystal'			=> 6000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_BUSTER_CANNON			=> array(
			'metal'			=> 50000,
			'crystal'			=> 50000,
			'deuterium'			=> 30000,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_SHIELD_SMALL			=> array(
			'metal'			=> 10000,
			'crystal'			=> 10000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_SHIELD_BIG			=> array(
			'metal'			=> 50000,
			'crystal'			=> 50000,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		DEFENCE_PROTECTOR			=> array(
			'metal'			=> 10000000,
			'crystal'			=> 5000000,
			'deuterium'			=> 2500000,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		MISSILE_INTERCEPTOR			=> array(
			'metal'			=> 8000,
			'crystal'			=> 0,
			'deuterium'			=> 2000,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		MISSILE_INTERPLANETARY			=> array(
			'metal'			=> 12500,
			'crystal'			=> 2500,
			'deuterium'			=> 10000,
			'energy'			=> 0,
			'factor'			=> 1,
		),
		RPG_GEOLOGUE			=> array(
			'max'			=> 20,
		),
		RPG_ADMIRAL			=> array(
			'max'			=> 20,
		),
		RPG_ENGINEER			=> array(
			'max'			=> 10,
		),
		RPG_TECHNOCRATE			=> array(
			'max'			=> 10,
		),
		RPG_CONSTRUCTOR			=> array(
			'max'			=> 3,
		),
		RPG_SCIENTIST			=> array(
			'max'			=> 3,
		),
		RPG_STOCKER			=> array(
			'max'			=> 2,
		),
		RPG_DEFENSER			=> array(
			'max'			=> 2,
		),
		RPG_BUNKER			=> array(
			'max'			=> 1,
		),
		RPG_ESPION			=> array(
			'max'			=> 2,
		),
		RPG_COMMANDANT			=> array(
			'max'			=> 3,
		),
		RPG_DESTRUCTOR			=> array(
			'max'			=> 3,
		),
		RPG_GENERAL			=> array(
			'max'			=> 5,
		),
		RPG_GEODESIST			=> array(
			'max'			=> 50,
		),
		RPG_AIDEDECAMP			=> array(
			'max'			=> 50,
		),
		RPG_RIDER			=> array(
			'max'			=> 1,
		),
		RPG_EMPEROR			=> array(
			'max'			=> 1,
		),
	);
	
	public static $battle_caps = array(
		SHIP_TRANSPORT_SMALL			=> array(
			'shield'			=> 10,
			'attack'			=> 5,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_TRANSPORT_BIG			=> array(
			'shield'			=> 25,
			'attack'			=> 5,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_HUNTER_LIGHT			=> array(
			'shield'			=> 10,
			'attack'			=> 50,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_HUNTER_HEAVY			=> array(
			'shield'			=> 25,
			'attack'			=> 150,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_CRUSHER			=> array(
			'shield'			=> 50,
			'attack'			=> 400,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 6,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 10,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_LINKOR			=> array(
			'shield'			=> 200,
			'attack'			=> 1000,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_COLONIZER			=> array(
			'shield'			=> 100,
			'attack'			=> 50,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_RECYCLER			=> array(
			'shield'			=> 10,
			'attack'			=> 1,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_SPY			=> array(
			'shield'			=> 1,
			'attack'			=> 0,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER				=> 1,
				SHIP_LINKOR				=> 1,
				SHIP_COLONIZER				=> 1,
				SHIP_RECYCLER				=> 1,
				SHIP_SPY				=> 1,
				SHIP_BOMBER				=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR				=> 1,
				SHIP_DEATH_STAR				=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER		=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_BOMBER			=> array(
			'shield'			=> 500,
			'attack'			=> 1000,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 20,
				DEFENCE_LASER_SMALL			=> 20,
				DEFENCE_LASER_BIG			=> 10,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 10,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_SOLAR_SATELITE			=> array(
			'shield'			=> 10,
			'attack'			=> 1,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_DESTRUCTOR			=> array(
			'shield'			=> 500,
			'attack'			=> 2000,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 2,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 10,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_DEATH_STAR			=> array(
			'shield'			=> 50000,
			'attack'			=> 200000,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 250,
				SHIP_TRANSPORT_BIG			=> 250,
				SHIP_HUNTER_LIGHT			=> 200,
				SHIP_HUNTER_HEAVY			=> 100,
				SHIP_CRUSHER			=> 33,
				SHIP_LINKOR			=> 30,
				SHIP_COLONIZER			=> 250,
				SHIP_RECYCLER			=> 250,
				SHIP_SPY			=> 1250,
				SHIP_BOMBER			=> 25,
				SHIP_SOLAR_SATELITE			=> 1250,
				SHIP_DESTRUCTOR			=> 5,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 15,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 200,
				DEFENCE_LASER_SMALL			=> 200,
				DEFENCE_LASER_BIG			=> 100,
				DEFENCE_GAUSS_CANNON			=> 50,
				DEFENCE_IONIC_CANNON			=> 100,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_LINECRUSHER			=> array(
			'shield'			=> 400,
			'attack'			=> 700,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 3,
				SHIP_TRANSPORT_BIG			=> 3,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 4,
				SHIP_CRUSHER			=> 4,
				SHIP_LINKOR			=> 7,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 5,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 1,
				DEFENCE_LASER_SMALL			=> 1,
				DEFENCE_LASER_BIG			=> 1,
				DEFENCE_GAUSS_CANNON			=> 1,
				DEFENCE_IONIC_CANNON			=> 1,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		SHIP_SUPERNOVA			=> array(
			'shield'			=> 200000,
			'attack'			=> 1000000,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 250,
				SHIP_TRANSPORT_BIG			=> 250,
				SHIP_HUNTER_LIGHT			=> 200,
				SHIP_HUNTER_HEAVY			=> 100,
				SHIP_CRUSHER			=> 33,
				SHIP_LINKOR			=> 30,
				SHIP_COLONIZER			=> 250,
				SHIP_RECYCLER			=> 250,
				SHIP_SPY			=> 1250,
				SHIP_BOMBER			=> 25,
				SHIP_SOLAR_SATELITE			=> 1250,
				SHIP_DESTRUCTOR			=> 5,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 15,
				SHIP_SUPERNOVA				=> 1,
				DEFENCE_MISSILE_LAUNCHER			=> 200,
				DEFENCE_LASER_SMALL			=> 200,
				DEFENCE_LASER_BIG			=> 100,
				DEFENCE_GAUSS_CANNON			=> 50,
				DEFENCE_IONIC_CANNON			=> 100,
				DEFENCE_BUSTER_CANNON			=> 1,
				DEFENCE_SHIELD_SMALL			=> 1,
				DEFENCE_SHIELD_BIG			=> 1,
				DEFENCE_PROTECTOR			=> 1,
			),
		),
		DEFENCE_MISSILE_LAUNCHER			=> array(
			'shield'			=> 20,
			'attack'			=> 80,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_LASER_SMALL			=> array(
			'shield'			=> 25,
			'attack'			=> 100,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_LASER_BIG			=> array(
			'shield'			=> 100,
			'attack'			=> 250,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_GAUSS_CANNON			=> array(
			'shield'			=> 200,
			'attack'			=> 1100,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_IONIC_CANNON			=> array(
			'shield'			=> 500,
			'attack'			=> 150,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_BUSTER_CANNON			=> array(
			'shield'			=> 300,
			'attack'			=> 3000,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_SHIELD_SMALL			=> array(
			'shield'			=> 2000,
			'attack'			=> 1,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_SHIELD_BIG			=> array(
			'shield'			=> 10000,
			'attack'			=> 1,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 1,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		DEFENCE_PROTECTOR			=> array(
			'shield'			=> 20000,
			'attack'			=> 1000000,
			'sd'			=> array(
				SHIP_TRANSPORT_SMALL			=> 1,
				SHIP_TRANSPORT_BIG			=> 1,
				SHIP_HUNTER_LIGHT			=> 1,
				SHIP_HUNTER_HEAVY			=> 1,
				SHIP_CRUSHER			=> 1,
				SHIP_LINKOR			=> 1,
				SHIP_COLONIZER			=> 1,
				SHIP_RECYCLER			=> 1,
				SHIP_SPY			=> 5,
				SHIP_BOMBER			=> 1,
				SHIP_SOLAR_SATELITE			=> 1,
				SHIP_DESTRUCTOR			=> 1,
				SHIP_DEATH_STAR			=> 1,
				SHIP_LINECRUSHER			=> 1,
				SHIP_SUPERNOVA				=> 1,
			),
		),
		MISSILE_INTERCEPTOR			=> array(
			'shield'			=> 1,
			'attack'			=> 1,
		),
		MISSILE_INTERPLANETARY			=> array(
			'shield'			=> 1,
			'attack'			=> 12000,
		),
	);
	
	public static $production = array(
		BUILDING_METALL_MINE			=> array(
			'metal'			=> 40,
			'crystal'			=> 10,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.5,
			'formule'			=> array(
				'metal'			=> 'return   (30 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
				'crystal'			=> 'return   "0";',
				'deuterium'			=> 'return   "0";',
				'energy'			=> 'return - (10 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
			),
		),
		BUILDING_CRYSTAL_MINE			=> array(
			'metal'			=> 30,
			'crystal'			=> 15,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.6,
			'formule'			=> array(
				'metal'			=> 'return   "0";',
				'crystal'			=> 'return   (20 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
				'deuterium'			=> 'return   "0";',
				'energy'			=> 'return - (10 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
			),
		),
		BUILDING_DEUTERIUM_SINTHEZER			=> array(
			'metal'			=> 150,
			'crystal'			=> 50,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.5,
			'formule'			=> array(
				'metal'			=> 'return   "0";',
				'crystal'			=> 'return   "0";',
				'deuterium'			=> 'return  ((10 * $BuildLevel * pow((1.1), $BuildLevel)) * (-0.002 * $BuildTemp + 1.28)) * (0.1 * $BuildLevelFactor);',
				'energy'			=> 'return - (20 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
			),
		),
		BUILDING_SOLAR_PLANT			=> array(
			'metal'			=> 50,
			'crystal'			=> 20,
			'deuterium'			=> 0,
			'energy'			=> 0,
			'factor'			=> 1.5,
			'formule'			=> array(
				'metal'			=> 'return   "0";',
				'crystal'			=> 'return   "0";',
				'deuterium'			=> 'return   "0";',
				'energy'			=> 'return   (20 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
			),
		),
		BUILDING_FUSION_PLANT			=> array(
			'metal'			=> 500,
			'crystal'			=> 200,
			'deuterium'			=> 100,
			'energy'			=> 0,
			'factor'			=> 1.8,
			'formule'			=> array(
				'metal'			=> 'return   "0";',
				'crystal'			=> 'return   "0";',
				'deuterium'			=> 'return - (10 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
				'energy'			=> 'return   (50 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);',
			),
		),
		SHIP_SOLAR_SATELITE			=> array(
			'metal'			=> 0,
			'crystal'			=> 2000,
			'deuterium'			=> 500,
			'energy'			=> 0,
			'factor'			=> 0.5,
			'formule'			=> array(
				'metal'			=> 'return   "0";',
				'crystal'			=> 'return   "0";',
				'deuterium'			=> 'return   "0";',
				'energy'			=> 'return  (($BuildTemp / 4) + 20) * $BuildLevel * (0.1 * $BuildLevelFactor);',
			),
		),
	);
	
	public static $stay_consumption = array(
		SHIP_TRANSPORT_SMALL	=> 5,
		SHIP_TRANSPORT_BIG	=> 5,
		SHIP_HUNTER_LIGHT	=> 2,
		SHIP_HUNTER_HEAVY	=> 7,
		SHIP_CRUSHER		=> 30,
		SHIP_LINKOR		=> 50,
		SHIP_COLONIZER		=> 100,
		SHIP_RECYCLER		=> 30,
		SHIP_SPY		=> 0.1,
		SHIP_BOMBER		=> 100,
		SHIP_DESTRUCTOR		=> 100,
		SHIP_DEATH_STAR		=> 0.1,
		SHIP_LINECRUSHER	=> 100,
		SHIP_SUPERNOVA		=> 100,
	);
	
	public static $resources = array(
		'build'			=> array(
			BUILDING_METALL_MINE,
			BUILDING_CRYSTAL_MINE,
			BUILDING_DEUTERIUM_SINTHEZER,
			BUILDING_SOLAR_PLANT,
			BUILDING_FUSION_PLANT,
			BUILDING_ROBOT_FACTORY,
			BUILDING_NANO_FACTORY,
			BUILDING_HANGAR,
			BUILDING_METAL_STORE,
			BUILDING_CRYSTAL_STORE,
			BUILDING_DEUTERIUM_STORE,
			BUILDING_LABORATORY,
			BUILDING_TERRAFORMER,
			BUILDING_ALLY_DEPOSIT,
			BUILDING_SILO,
			BUILDING_MONDBASIS,
			BUILDING_PHALANX,
			BUILDING_SPRUNGTOR,
		),
		'tech'			=> array(
			TECH_SPY,
			TECH_COMPUTER,
			TECH_MILITARY,
			TECH_SHIELD,
			TECH_DEFENCE,
			TECH_ENERGY,
			TECH_HYPERSPACE,
			TECH_COMBUSTION,
			TECH_IMPULSE_DRIVE,
			TECH_HYPERSPACE_DRIVE,
			TECH_LASER,
			TECH_IONIC,
			TECH_BUSTER,
			TECH_INTERGALACTIC,
			TECH_EXPEDITION,
			TECH_COLONIZATION,
			TECH_GRAVITON,
		),
		'fleet'			=> array(
			SHIP_TRANSPORT_SMALL,
			SHIP_TRANSPORT_BIG,
			SHIP_HUNTER_LIGHT,
			SHIP_HUNTER_HEAVY,
			SHIP_CRUSHER,
			SHIP_LINKOR,
			SHIP_COLONIZER,
			SHIP_RECYCLER,
			SHIP_SPY,
			SHIP_BOMBER,
			SHIP_SOLAR_SATELITE,
			SHIP_DESTRUCTOR,
			SHIP_DEATH_STAR,
			SHIP_LINECRUSHER,
	//		SHIP_SUPERNOVA,
		),
		'defense'			=> array(
			DEFENCE_MISSILE_LAUNCHER,
			DEFENCE_LASER_SMALL,
			DEFENCE_LASER_BIG,
			DEFENCE_GAUSS_CANNON,
			DEFENCE_IONIC_CANNON,
			DEFENCE_BUSTER_CANNON,
			DEFENCE_SHIELD_SMALL,
			DEFENCE_SHIELD_BIG,
	//		DEFENCE_PROTECTOR,
			MISSILE_INTERCEPTOR,
			MISSILE_INTERPLANETARY,
		),
		'officier'			=> array(
			RPG_GEOLOGUE,
			RPG_ADMIRAL,
			RPG_ENGINEER,
			RPG_TECHNOCRATE,
			RPG_CONSTRUCTOR,
			RPG_SCIENTIST,
			RPG_STOCKER,
			RPG_DEFENSER,
	//		RPG_BUNKER,
			RPG_ESPION,
			RPG_COMMANDANT,
			RPG_DESTRUCTOR,
			RPG_GENERAL,
			RPG_GEODESIST,
			RPG_AIDEDECAMP,
	//		RPG_RIDER,
	//		RPG_EMPEROR,
		),
		'prod'			=> array(
			BUILDING_METALL_MINE,
			BUILDING_CRYSTAL_MINE,
			BUILDING_DEUTERIUM_SINTHEZER,
			BUILDING_SOLAR_PLANT,
			BUILDING_FUSION_PLANT,
			SHIP_SOLAR_SATELITE,
		),
	);

	public static function get_resources($types = array('all'))
	{
		$all = (is_string($types) && $types == 'all') || (is_array($types) && reset($types) == 'all');

		if(!$all && (!is_array($types) || sizeof($types) == 1))
		{
			if(is_string($types) && isset(self::$resources[$types]))
				return self::$resources[$types];
			else if(is_array($types) && isset(self::$resources[$resource_type = reset($types)]))
				return self::$resources[$resource_type];
			else
				return array();
		}		

		$merge = array();
		if($all)
		{
			foreach(self::$resources as $resource_type => $resources)
			{
				$merge = array_merge($merge, $resources);
			}
		}
		else
		{
			foreach($types as $resource_type)
			{
				if(isset(self::$resources[$resource_type]))
					$merge = array_merge($merge, self::$resources[$resource_type]);
			}
		}

		return $merge;
	}

	public static function get_db_fields($types = array('all'), $with_prefix = false)
	{
		if(!is_array($types))
			$types = array($types);

		$all = isset($types[0]) && $types[0] == 'all';

		$merge = array();
		if($all)
		{
			foreach(self::$resources as $resource_type => $resources)
			{
				foreach($resources as $resource_id)
				{
					// We never must never use one prefix for all fields
					$merge[] = self::$db_fields[$resource_id];
				}
			}
		}
		else
		{
			foreach($types as $prefix => $resource_type)
			{
				foreach(self::$resources[$resource_type] as $resource_id)
				{
					$merge[] = ($with_prefix ? $prefix . "." : '') . self::$db_fields[$resource_id];
				}
			}
		}

		return implode(", ", $merge);
	}
}

?>